- name: Install system requirements
  apt:
    name:
      - python3-setuptools
      - python3-pip
      - python3-gpiozero
      - git
    update_cache: yes
    #upgrade: dist
    install_recommends: no
