- name: "Reboot"
  command: shutdown -r now "Ansible reboot"
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for it to come back
  local_action: wait_for host={{ansible_ssh_host}} state=started port=22 delay=30 timeout=300 connect_timeout=15
  when: reboot_wait is defined | bool == True
